#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Roman C. Podolski <mailto:roman.podolski@tum.de>

def options(opt):
    pass


def configure(conf):
    conf.check_cxx(lib="gps")
    conf.check_cxx(lib="glog")
    conf.check_cxx(lib="gflags")

    conf.check_cfg(atleast_pkgconfig_version='0.0.0')
    conf.check_cfg(package='eigen3', args=['--cflags'])

    conf.env.CXXFLAGS=['-std=c++14','-Wall','-pedantic','-O2']

def build(bld):
    bld(features='cpplint', source=bld.path.parent.ant_glob('include/*/*.h'))

    bld.objects(
       features='cpplint',
       target='planner',
       source=bld.path.ant_glob('**/planner/*.cc', excl=['**/*_main.cc']),
       includes='. ../include',
    )

    bld.program(
        features='cpplint',
        target='playground',
        source='playground_main.cc',
        includes ='. ../include ../proto ../3rdparty',
        use='planner BOOST GLOG GFLAGS',
    )
